[hololens]
package = "holo/lens-mkdocs"
requirements = [
    "mkdocs-material",
    "mkdocs-awesome-pages-plugin",
    "fontawesome_markdown",
    "mdx_truly_sane_lists",
    "mkdocs-macros-plugin"
]

[hololens.output]
merge = "replace"
